name: locomotion-lecture

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10
  - scipy
  - matplotlib
  - mujoco
  - pinocchio
  - jupyter
  - "gymnasium == 1.0.0"
  - numpy
  - pyqtgraph
  - PyQt5
  - casadi
